### ISSUE TITLE
Remapping or removing internal ds-test will break intellisense

### ISSUE THREAD

**Issue by jordaniza** [foundry-rs/forge-std#194]
Version: forge 0.2.0 (f19fd81 2022-10-06T00:10:55.884113912Z)
OS: Linux
Editor: VS Code with Juan Blanco Solidity Extension

Problem: Remapping or removing internal ds-test will break intellisense

Details:

On a fresh build of foundry, running `forge remappings > remappings.txt` will give the following:

```
ds-test/=lib/forge-std/lib/ds-test/src/
forge-std/=lib/forge-std/src/
```

All good. However, the first line is a bit problematic for VS code users. 

If you change or delete the ds-test remapping, the language server cannot resolve the import path in, for example: `lib/forge-std/src/Test.sol`, this will lead to broken intellsense/autocompletion etc etc. It's a bit of a pain to debug as you don't get any error messages in the editor (although certain compiler configurations refuse to compile).

Possible Solutions:

One option would be to make the import path for ds-test in the forge-std library explicit (`lib/forge-std/lib/ds-test/src/`). This would avoid the need for remappings so the user cannot break it. The code in the std lib would be *slightly* less concise, but adds resilience and 'just works'.

Alternatively, update the docs https://book.getfoundry.sh/projects/dependencies to indicate that the ds-test remapping should not be changed. I don't love this as it's basically RTFM, but it would hopefully help a few people

**Comment by mds1** [comment]
Why do you want to change the ds-test remapping? In general you shouldn't need to touch this, but if you want to open an issue/PR in the book to explicitly mention not to touch it that seems ok to me 🙂

**Comment by jordaniza** [comment]
I don't but you *can*. 

They get loaded into the remappings.txt file which is required for VS code to detect aliased imports.

Because there is no warning that the ds-test mappings should not be changed, it's possible to break intellisense in the project purely by accident. 

Essentially you have a sharp corner with no obvious warning signs and that is why I'm raising the issue, it's a hit on the otherwise wonderful developer experience.

**Comment by mds1** [comment]
IMO `remappings.txt` should be considered deprecated and not used. Remappings can be customized with the `remappings` key in the config file, and the text file approach was originally for backwards compatibility with dapptools. In general, you shouldn't need to worry about remappings unless you have hybrid foundry-hardhat project and need to point foundry to `node_modules`

Given that, I'd say the linked section of the book that says "You can customize these remappings by creating a `remappings.txt` file in the root of your project" should be updated

TBH I've never consistently gotten most intellisense features working in foundry projects, the main reason afaik is because solidity lacks a proper LSP so extensions have to hack these intellisense features together with assumptions, and perhaps "look for remappings in remappings.txt is one of those assumptions". I'd assume there are many other things that can confuse intellisense too

Regardless, I don't think there's anything we need to change in forge-std here (personally not a fan of forcing absolute paths, since all deps you install will have a similar default remapping anyway), but if you want to open an issue/PR in the [book](https://github.com/foundry-rs/book) to clarify things that's fine with me
