### ISSUE TITLE
`Nested arrays not yet implemented.` error crashing compilation against solc 0.6.x

### ISSUE THREAD

**Issue by lukaszh2o** [foundry-rs/forge-std#215]
Changes introduced in PR #184 - commit https://github.com/foundry-rs/forge-std/commit/17656a2fa5453f495d8c1302a0cedded912457eb , seems to be causing issues with compilation using Solc 0.6x (tested with 0.6.2, 0.6.7, 0.6.9, 0.6.10).

Each one of them fails to compile, either by `UnimplementedFeatureError: Nested arrays not yet implemented.` error. Including `pragma experimental ABIEncoderV2;` in compiled file results instead in `YulException: Stack too deep when compiling inline assembly: Variable dataEnd is 1 slot(s) too deep inside the stack.`

Preceding commit works just fine (https://github.com/foundry-rs/forge-std/commit/2a2ce3692b8c1523b29de3ec9d961ee9fbbc43a6)

**Comment by mds1** [comment]
Hmm this is interesting:
- CI passes, which builds with 0.6.2, 0.7.0, 0.7.6, and 0.8.0. You can see the successful builds from [this run](https://github.com/foundry-rs/forge-std/actions/runs/3423470902/jobs/5702099070) I just did
- But running those commands on my machine locally against the forge-std repo (macOS, not M1), all `forge build --skip test --use solc:0.X.Y` commands fail for any of those four versions. Specifically, 0.6.2 and 0.7.0 give `UnimplementedFeatureError: Nested arrays not yet implemented.` and the others give stack too deep
- No errors if I locally run `forge build --skip test` which compiles with 0.8.17

pinging @leonardoalt in case anything comes to mind about why this might happen? It doesn't seem related to #207, though the difference in CI vs. local results does make me wonder if it's related to the different solc binaries being used?

cc'ing @nventuro for awareness since I know you had the same issue

**Comment by leonardoalt** [comment]
From the top of my head, my first guess would be that the new foundry lib code causes stack too deep in old compiler versions that didn't have the current optimizers, that is, the error messages are legit for older Solc versions. But if CI passes for 0.6.2 this might be wrong, so need to take a better look.

**Comment by mds1** [comment]
Ok, confirmed this is a forge-std issue. The reason CI passed it because it never compiled a contract that inherited from `Test` with older solc versions (since `Test` is abstract it wasn't compiled in CI, and we don't compile tests with lower versions).

I noticed/confirmed this when working on #217. The `(string[2][] memory rpcs) = vm.rpcUrls();` line is the culprit. If anyone needs to reproduce, pull the forge-std version in #217, comment out everything in `_constructor()` except for that line, then run `forge build --skip test --use solc:0.8.0`.
