### ISSUE TITLE
Version 1.1.0 to set in package.json ?

### ISSUE THREAD

**Issue by eden91940** [foundry-rs/forge-std#219]
https://github.com/foundry-rs/forge-std/blob/33d4895fb629aabf12e0f60740367bd03e702bd1/package.json#L3

**Comment by ZeroEkkusu** [comment]
If the version is in `package.json` doesn’t matter, we can also set it to `”V1”`.

**Comment by mds1** [comment]
Since we're not publishing to NPM currently, this doesn't matter much, but it will matter if/when we do start publishing to npm (https://github.com/foundry-rs/forge-std/issues/39, https://github.com/foundry-rs/forge-std/issues/170). So let's PR in a change to `"1.1.0"` to keep it in sync for good measure, but I don't think we need to do a new release/tag just for this
