### ISSUE TITLE
Feature Request: support pairing a string with bytes in console2.log

### ISSUE THREAD

**Issue by joejordan** [foundry-rs/forge-std#308]
Most of my console2.log usage consists of using a string to describe the output, and then outputting the variable next to it.

The log function has many overrides handling many different variable types, so I usually don't have to think when printing an address or a uint, i.e.
```solidity
console2.log("admin address", address(0x69));
console2.log("admin balance", address(0x69).balance);
```

However there are no overrides for a string with byte1-byte32 (ex: `"log(string,bytes32)"`) or the variable length `bytes`, i.e. `"log(string,bytes)"`, requiring me to console log a first line with the variable description and a second line for the bytes output.

My request is that we include `console2.log` overrides for a string variable paired with fixed and variable bytes variables to allow for expanded use of this use case.

**Comment by mds1** [comment]
There are `console.logBytes32` and `console.logBytes` methods. The reason they are not overloads of `console.log` is because then `console2.log("text")` becomes ambiguous, as solidity does not know if that is a `string` or `bytes`, so then you'd have to do `console2.log(string("text"))`.

Note that you can also use solidity's `string.concat` and `vm.toString(myBytes)` which may also be useful
