### ISSUE TITLE
Slow compilation with via-ir

### ISSUE THREAD

**Issue by zeroknots** [foundry-rs/forge-std#321]
Currently trying to integrate Uniswap's universal router. https://github.com/Uniswap/universal-router

Working with this code requires via-ir. Unfortunately I am experiencing extremely slow compile times:

reproduce:
```sh
git clone git@github.com:Uniswap/universal-router.git
cd universal-router
forge install
forge build
...
[⠰] Compiling 83 files with 0.8.17
[⠑] Solc 0.8.17 finished in **78.06s** <-- makes me sad
```

Compiling with hardhat:
pnpm compile --force  **19.11s** user 0.45s system 105% cpu 18.468 total

Versions:
forge 0.2.0 (28b2ae6 2023-03-06T00:04:30.253422Z)
solc 0.8.17

I assume this might be related to https://github.com/foundry-rs/forge-std/issues/225

**Comment by mds1** [comment]
This reproduction case doesn't demonstrate that forge-std is the issue here. It seems to me that `forge build` is a lot slower because it's compiling many solidity source AND solidity test files with via-ir (which you can workaround using the apporach @PaulRBerg mentioned), whereas hardhat is only compiling source files.

Looking at the recent successful CI runs in this repo, the via-ir builds of forge-std still only take 5 seconds (at the time of #225 it was 30-90 seconds)
