### ISSUE TITLE
Support for contracts with solc < 0.6.2

### ISSUE THREAD

**Issue by yvonnezhangc** [foundry-rs/forge-std#361]
Not an issue but a question:

Currently in the master branch, the `Test.sol` explicitly [requires](https://github.com/foundry-rs/forge-std/blob/master/src/Test.sol) solidity complier version >= 0.6.2.

Given this, would it still be possible to test legacy contracts deployed using a lower complier version? Any known solutions such as using an earlier forge-std version? Any known issues?

Would be helpful if this is documented somewhere also. Thank you!

**Comment by mds1** [comment]
My suggestion would be to fork this repo and make change to get things compiling with the version that you need. 

The main reason I recall we started at compiler version 0.6.2 was because that's when interface inheritance was [introduced](https://github.com/ethereum/solidity/blob/develop/Changelog.md#062-2020-01-27), which we use in `interface Vm is VmSafe`.

Prior to that bump the min was `>= 0.6.0` which [introduced](https://github.com/ethereum/solidity/blob/develop/Changelog.md#060-2019-12-17) a lot of changes, like the `virtual` and `override` keywords. So there will probably be a good set of changes you'll need. Easiest way is probably just compile with your version and keep fixing everything solc complains about, which likely will be tedious. 

I'm going to close this issue since this repo won't add support for versions below 0.6.2, but feel free to ask here if you have any more questions
