### ISSUE TITLE
Alphabetical ordering and NatSpec in Vm

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/forge-std#459]
The current `Vm` does not have any particular structuring logic besides the `Vm` <> `VmSafe` dichotomy. When adding new cheats, it is unclear where they should be added.

Similarly, it would be nice if the comments used the NatSpec tag `@dev`, so that we get syntax highlighting (via VSCode extensions) and the ability to automatically generate a documentation UI with `forge doc` if we ever decide that we want to do this.

I happen to maintain an alphabetically ordered + NatSpec tagged implementation in PRBTest:

https://github.com/PaulRBerg/prb-test/blob/8d76ad63d1bfa0b16bb880cfe4620a9e7e6aaa19/src/Vm.sol

So, adhering to these two principles would also make it easier to keep my implementation in sync with Forge Std.

**Comment by PaulRBerg** [comment]
See https://github.com/PaulRBerg/prb-test/pull/33

**Comment by PaulRBerg** [comment]
See https://github.com/PaulRBerg/prb-test/pull/33

**Comment by ruvaag** [comment]
I thought they were grouped by category like how the foundry book groups cheats, but this isn't strictly enforced. Maybe grouping by category and sorting them alphabetically within groups so it doesn't turn into one big chunk of cheats?

**Comment by mds1** [comment]
@PaulRBerg what do you like about alphabetical ordering? It feels strictly worse to me because:
1. If you're looking for a specific cheat, you'd just cmd+F it anyway
2. It reduces discoverability, like @ruvaag said we tried to group cheats by category, so this makes it easy to find all cheats involving block properties, or the filesystem, etc

There are probably improvements to the groupings we currently have, e.g. making them more explicit, with consistent comment separators, and fixing out of place ones. I'd be supportive of a PR that cleans that up, but I don't think alphabetical as in https://github.com/foundry-rs/forge-std/pull/461 is the way to go

**Comment by PaulRBerg** [comment]
> you'd just cmd+F it anyway

Well, that's the thing - I've trained myself not to use CMD+F that often, primarily because I use alphabetical ordering everywhere. And my guess is that, all else being equal, all English speakers would use CMD+F less often when code is alphabetically ordered.

But anyway. I agree it's a minor issue in the grand scheme of things.

> It reduces discoverability

Fair point. But it also increases maintainability as per the OP (unclear where to add new cheats, having to remember to group them, etc.)

**Comment by mds1** [comment]
Thanks. I do still think it's worth keeping the logical grouping instead of alphabetical, and I'll start being better at enforcing the ordering going forward. I'll also create an issue to clean up the existing `Vm` file and will tackle that soon. Going to close this as a result :)
