### ISSUE TITLE
#51 breaks backwards compatibility before `0.8.0`

### ISSUE THREAD

**Issue by ernestognw** [foundry-rs/forge-std#53]
## Description

Recently #51 was merged and it included an `unchecked` in the `stdMath.abs` function, which requires to bump the Solidity version for the `forge-std` package to be `pragma solidity >=0.8.0 <0.9.0;` instead of `pragma solidity >=0.6.0 <0.9.0;`

I'm myself running into an issue here since I wanted to test a `0.6.0` contract and this was broken. You either will need to remove the `unchecked` or bump the version.

**Comment by mds1** [comment]
Great catch, thanks! Seems we can just change the `abs` method to ` return a >= 0 ? a : -a;` and be all set? I can get a PR open for that tomorrow unless you want to beat me to it.

@ZeroEkkusu We should probably update the CI to run against a few different solc versions, since this has happened before

**Comment by OliverNChalk** [comment]
If you don't have unchecked, the following will fail:

```solidity
int256 inverse = -(type(int256).min)
```

**Comment by ernestognw** [comment]
> If you don't have unchecked, the following will fail:
> 
> ```solidity
> int256 inverse = -(type(int256).min)
> ```

This is correct.
Here's my 20 wei (#54)

**Comment by OliverNChalk** [comment]
Assuming we don't want to raise the minimum solidity version, I'm leaning towards #54
