### ISSUE TITLE
Feature request: block gas limits for most popular chains

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/forge-std#535]
Block gas limits can influence the configuration of smart contracts. For example, the [`MAX_SEGMENT_COUNT`](https://github.com/sablier-labs/v2-core/blob/0a75661bc77f087620567265e1c7f973b1c504a8/src/SablierV2LockupDynamic.sol#L55C39-L55C56) in Sablier is influenced by them.

Thus, it would be handy if Forge Std offered the block gas limits of the most popular chains (Ethereum, Arbitrum, Optmism, etc.) as fields in the [`Chain`](https://github.com/foundry-rs/forge-std/blob/e4aef94c1768803a16fe19f7ce8b65defd027cfd/src/StdChains.sol#L45-L57) struct.

**Comment by mds1** [comment]
For L1 chains, block gas limits are soft consensus parameters with no easy visibility, so I'm hesitant to add them since they're likely become out of date.

For OP Stack chains, you can read this value for a given chain by calling the `gasLimit` getter on the L1 SystemConfig contract. For example with OP Mainnet, the L1 SystemConfig contract address can be found [here](https://github.com/ethereum-optimism/superchain-registry/blob/6558fda88c2e5994bd15ad6fbef88af3ff6e37e4/superchain/extra/addresses/mainnet/op.json#L10), and you can call
```
$ cast call 0x229047fed2591dbec1eF1118d64F7aF3dB9EB290 "gasLimit()(uint256)"
30000000
```

Arbitrum stack chains may expose this value similarly but I'm unsure offhand

**Comment by PaulRBerg** [comment]
Ok, in this case it makes sense to close this issue.

Thanks for your guidance on reading the gas limit on OP Stack chains. Didn't know about the `gasLimit` getter.
